### ISSUE TITLE
Draw.io files get overwritten by new ones

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub-modules-drawio#7] opened 2020-04-01 14:01 UTC
- HH 1.4.4 
- Create multiple draw.io documents within a Space to reproduce

**Comment by VCRP-fetzer** [comment] 2024-04-15 14:31
I'm sorry to say it, but the module seems to be in a terrible condition. In my tests, the behavior described in this issue occurs reproducable, i.e. the last saved Draw.io file overwrites **all** Draw.io files in a folder. Here is a short screencast:

@luke- The module should not be offered in the Marketplace in this state.

https://github.com/humhub-contrib/drawio/assets/109344327/0cd6495d-1f97-49b9-825d-9a6b147d96ec

(Another effect you can see in the screencast is that after creating a new file Draw.io displays the content of an old test file). Not sure if this is related to this issue.)

**Comment by luke-** [comment] 2024-04-15 15:18
We'll take a look and either mark it depracted soon or update it.

**Comment by VCRP-fetzer** [comment] 2024-04-15 15:24
Thanks. I have to add that Draw.io is a fine tool and it would be a nice and welcome addition to Humhub.

**Comment by yurabakhtin** [comment] 2024-04-17 12:49
@luke- Fixed in the PR https://github.com/humhub-contrib/drawio/issues/7

**Closed as completed** 2024-04-17 13:16 UTC
Labels: bug

**Comment by VCRP-fetzer** [comment] 2024-04-18 08:03
Thank you!
